M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date utorak, 02. siječnja 2024. 16:00:07 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-02T16:00:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X162.243Y-81.535
X162.243Y-90.996
T2
X229.957Y-87.583
X239.357Y-81.283
T3
X255.751Y-87.004
X255.751Y-123.004
M30
